name: Plan Terraform
on:
  push
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
     - name: Terraform plan
       id: plan
       if: github.event_name == 'pull_request'
       run: terraform plan -no-color -input=false
       continue-on-error: true